### ISSUE TITLE
Scroll jumps to start whenever data changes or on hot reload

### ISSUE THREAD

**Issue by Tech-Tac** [dridino/smooth_list_view#6]
SmoothListView.builder, adding elements to the data makes the view jump to the starting position, also when hot reloading.

**Comment by dridino** [comment]
Thanks again for taking the time to submit an issue.
The issue making the list jump to the starting position when adding an element is also solved with the new version of the package, let me know if it's okay for you.
The fact that the list jumps to the starting position when hot reloading is its normal behaviour, since a hot reload causes the widget tree to be rebuilt, and so is the `SmoothListView`. A classic `ListView` behaves the same.

**Comment by Tech-Tac** [comment]
Thanks for fixing
